Repository cse110-sp21-group12/cse110-sp21-group12, pull requests merged in 2021-06, with the labels that each got.

#109 Deploying i101
  index.html
Labels: enhancement

#125 fixed new line problem in notes
  source/DailyOverview/DailyJS.js
  source/DailyOverview/note.js
Labels: bug, frontend

#126 Testing basics i113
  .github/workflows/testing.yml
  .gitignore
  jest-puppeteer.config.js
  package-lock.json
  source/Backend/BackendInit.js
  source/Backend/MockData.json
  source/DailyOverview/DailyOverview.html
  source/DailyOverview/bullet.js
  source/Login/LoginJS.js
  source/MonthlyOverview/MonthlyOverview.html
  source/YearlyOverview/YearlyOverview.html
  source/tests/PuppTests.test.js
  source/tests/sample.test.js
  source/tests/sampleP.test.js
Labels: CI/CD, testing
